<?php
session_start();

if(!isset($_SESSION['mobile'])){
	Header("Location:./index.php");
	exit;
}elseif(isset($_SESSION['finished'])){
	Header("Location:./thanks.html");
	exit;
}elseif(!isset($_SESSION['select'])||$_SESSION['select']!=1){
	Header("Location:./select.php");
	exit;
}elseif(isset($_POST['step'])&&$_POST['step']=='questionz'){
	//save value to session
	saveQuestionz();
	
	//不允许再次填写
	//$_SESSION['finished']=true;
	//允许换手机号再填
	session_destroy();
	
	Header("Location:./thanks.html");
	exit;
}

function saveQuestionz(){
	$con = mysql_connect("localhost","root","");
	if (!$con){
		die('Could not connect: ' . mysql_error());
	}
	mysql_query("set character set 'utf-8'");//读库
	mysql_query("set names 'utf-8'");//写库
	mysql_select_db("vote", $con);
	if(!mysql_query("insert into `vote`.`vote_baseinfo` (`mobile`, `sex`, `age`, `profession`, `city`, `county`, `created`, `ip`)values ('".$_SESSION['mobile']."', '".$_SESSION['sex']."', '".$_SESSION['age']."', '".$_SESSION['profession']."', 1, 0, now(), '".getip()."');")){
		die('Error: ' . mysql_error());
	}
	if (!mysql_query("insert into `vote`.`vote_questionz` (`mobile`, `z01`, `z02`, `z03`, `z04`, `z05`, `z06`, `z07`, `z08`, `z09`, `z10`, `z11`, `z12`, `z13`, `z14`, `z15`, `z16`, `z17`, `z18`, `z19`, `z20`, `z21`, `z22`, `z23`, `z24`, `z25`, `z26`, `z27`, `z28`, `z29`, `z30`, `z31`, `z32`, `z33`, `z34`, `z35`, `z36`, `z37`, `z38`, `z39`, `z40`, `z41`, `z42`, `z43`, `z44`, `z45`, `z46`, `z47`, `z48`, `z49`, `z50`, `z51`, `z52`, `z53`, `z54`, `z55`, `z56`, `z57`, `z58`, `z59`, `z60`, `z61`, `z62`, `z63`, `z64`, `z65`, `z66`, `z67`, `z68`, `z69`, `z70`, `z71`, `z72`, `z73`, `z74`, `z75`, `z76`, `z77`, `z78`, `z79`, `z80`, `z81`, `z82`, `z83`, `z84`, `z85`, `z86`, `z87`, `suggest`, `created`)values ('".$_SESSION['mobile']."', '".$_POST['z01']."', '".$_POST['z02']."', '".$_POST['z03']."', '".$_POST['z04']."', '".$_POST['z05']."', '".$_POST['z06']."', '".$_POST['z07']."', '".$_POST['z08']."', '".$_POST['z09']."', '".$_POST['z10']."', '".$_POST['z11']."', '".$_POST['z12']."', '".$_POST['z13']."', '".$_POST['z14']."', '".$_POST['z15']."', '".$_POST['z16']."', '".$_POST['z17']."', '".$_POST['z18']."', '".$_POST['z19']."', '".$_POST['z20']."', '".$_POST['z21']."', '".$_POST['z22']."', '".$_POST['z23']."', '".$_POST['z24']."', '".$_POST['z25']."', '".$_POST['z26']."', '".$_POST['z27']."', '".$_POST['z28']."', '".$_POST['z29']."', '".$_POST['z30']."', '".$_POST['z31']."', '".$_POST['z32']."', '".$_POST['z33']."', '".$_POST['z34']."', '".$_POST['z35']."', '".$_POST['z36']."', '".$_POST['z37']."', '".$_POST['z38']."', '".$_POST['z39']."', '".$_POST['z40']."', '".$_POST['z41']."', '".$_POST['z42']."', '".$_POST['z43']."', '".$_POST['z44']."', '".$_POST['z45']."', '".$_POST['z46']."', '".$_POST['z47']."', '".$_POST['z48']."', '".$_POST['z49']."', '".$_POST['z50']."', '".$_POST['z51']."', '".$_POST['z52']."', '".$_POST['z53']."', '".$_POST['z54']."', '".$_POST['z55']."', '".$_POST['z56']."', '".$_POST['z57']."', '".$_POST['z58']."', '".$_POST['z59']."', '".$_POST['z60']."', '".$_POST['z61']."', '".$_POST['z62']."', '".$_POST['z63']."', '".$_POST['z64']."', '".$_POST['z65']."', '".$_POST['z66']."', '".$_POST['z67']."', '".$_POST['z68']."', '".$_POST['z69']."', '".$_POST['z70']."', '".$_POST['z71']."', '".$_POST['z72']."', '".$_POST['z73']."', '".$_POST['z74']."', '".$_POST['z75']."', '".$_POST['z76']."', '".$_POST['z77']."', '".$_POST['z78']."', '".$_POST['z79']."', '".$_POST['z80']."', '".$_POST['z81']."', '".$_POST['z82']."', '".$_POST['z83']."', '".$_POST['z84']."', '".$_POST['z85']."', '".$_POST['z86']."', '".$_POST['z87']."', '".$_POST['suggest']."', now());")){
		die('Error: ' . mysql_error());
	}
	mysql_close($con);
}

function getip() {
	$unknown = 'unknown';
	if ( isset($_SERVER['HTTP_X_FORWARDED_FOR'])
			&& $_SERVER['HTTP_X_FORWARDED_FOR']
			&& strcasecmp($_SERVER['HTTP_X_FORWARDED_FOR'],
					$unknown) ) {
						$ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
					} elseif ( isset($_SERVER['REMOTE_ADDR'])
							&& $_SERVER['REMOTE_ADDR'] &&
							strcasecmp($_SERVER['REMOTE_ADDR'], $unknown) ) {
								$ip = $_SERVER['REMOTE_ADDR'];
					}
					if (false !== strpos($ip, ','))
						$ip = reset(explode(',', $ip));
						return $ip;
}
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>廊坊市干部考核社会评价调查系统</title>
	<link href="./css/main.css" type="text/css" rel="stylesheet">
	<script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.min.js"></script>
	<script type="text/javascript" src="./js/check.js"></script>
</head>
<body bgcolor=white lang=ZH-CN>
	<p class=title align=center>
		市直单位领导班子评价
	</p>

	<div class=main>
		<form id="user_login" action="" method="post">

			<p class=sub_title><b>一、总体评价。请对所列单位领导班子进行评价，如不选择默认为不了解。</b></p>
			<table>
				<tr><td><p class=txt><b class=blue>1、市纪委（监察局）</b></p></td><td><p class=select><label><input type=radio name="z01" value=4 />优秀</label>&nbsp;<label><input type=radio name="z01" value=3 />良好</label>&nbsp;<label><input type=radio name="z01" value=2 />一般</label>&nbsp;<label><input type=radio name="z01" value=1 />较差</label>&nbsp;<label><input type=radio name="z01" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>2、市委办公室</b></p></td><td><p class=select><label><input type=radio name="z02" value=4 />优秀</label>&nbsp;<label><input type=radio name="z02" value=3 />良好</label>&nbsp;<label><input type=radio name="z02" value=2 />一般</label>&nbsp;<label><input type=radio name="z02" value=1 />较差</label>&nbsp;<label><input type=radio name="z02" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>3、市政府办公室</b></p></td><td><p class=select><label><input type=radio name="z03" value=4 />优秀</label>&nbsp;<label><input type=radio name="z03" value=3 />良好</label>&nbsp;<label><input type=radio name="z03" value=2 />一般</label>&nbsp;<label><input type=radio name="z03" value=1 />较差</label>&nbsp;<label><input type=radio name="z03" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>4、市人大机关</b></p></td><td><p class=select><label><input type=radio name="z04" value=4 />优秀</label>&nbsp;<label><input type=radio name="z04" value=3 />良好</label>&nbsp;<label><input type=radio name="z04" value=2 />一般</label>&nbsp;<label><input type=radio name="z04" value=1 />较差</label>&nbsp;<label><input type=radio name="z04" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>5、市政协机关</b></p></td><td><p class=select><label><input type=radio name="z05" value=4 />优秀</label>&nbsp;<label><input type=radio name="z05" value=3 />良好</label>&nbsp;<label><input type=radio name="z05" value=2 />一般</label>&nbsp;<label><input type=radio name="z05" value=1 />较差</label>&nbsp;<label><input type=radio name="z05" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>6、市委组织部</b></p></td><td><p class=select><label><input type=radio name="z06" value=4 />优秀</label>&nbsp;<label><input type=radio name="z06" value=3 />良好</label>&nbsp;<label><input type=radio name="z06" value=2 />一般</label>&nbsp;<label><input type=radio name="z06" value=1 />较差</label>&nbsp;<label><input type=radio name="z06" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>7、市委宣传部</b></p></td><td><p class=select><label><input type=radio name="z07" value=4 />优秀</label>&nbsp;<label><input type=radio name="z07" value=3 />良好</label>&nbsp;<label><input type=radio name="z07" value=2 />一般</label>&nbsp;<label><input type=radio name="z07" value=1 />较差</label>&nbsp;<label><input type=radio name="z07" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>8、市委统战部</b></p></td><td><p class=select><label><input type=radio name="z08" value=4 />优秀</label>&nbsp;<label><input type=radio name="z08" value=3 />良好</label>&nbsp;<label><input type=radio name="z08" value=2 />一般</label>&nbsp;<label><input type=radio name="z08" value=1 />较差</label>&nbsp;<label><input type=radio name="z08" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>9、市委农工部</b></p></td><td><p class=select><label><input type=radio name="z09" value=4 />优秀</label>&nbsp;<label><input type=radio name="z09" value=3 />良好</label>&nbsp;<label><input type=radio name="z09" value=2 />一般</label>&nbsp;<label><input type=radio name="z09" value=1 />较差</label>&nbsp;<label><input type=radio name="z09" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>10、市委政法委</b></p></td><td><p class=select><label><input type=radio name="z10" value=4 />优秀</label>&nbsp;<label><input type=radio name="z10" value=3 />良好</label>&nbsp;<label><input type=radio name="z10" value=2 />一般</label>&nbsp;<label><input type=radio name="z10" value=1 />较差</label>&nbsp;<label><input type=radio name="z10" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>11、市委研究室</b></p></td><td><p class=select><label><input type=radio name="z11" value=4 />优秀</label>&nbsp;<label><input type=radio name="z11" value=3 />良好</label>&nbsp;<label><input type=radio name="z11" value=2 />一般</label>&nbsp;<label><input type=radio name="z11" value=1 />较差</label>&nbsp;<label><input type=radio name="z11" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>12、市直工委</b></p></td><td><p class=select><label><input type=radio name="z12" value=4 />优秀</label>&nbsp;<label><input type=radio name="z12" value=3 />良好</label>&nbsp;<label><input type=radio name="z12" value=2 />一般</label>&nbsp;<label><input type=radio name="z12" value=1 />较差</label>&nbsp;<label><input type=radio name="z12" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>13、市编办</b></p></td><td><p class=select><label><input type=radio name="z13" value=4 />优秀</label>&nbsp;<label><input type=radio name="z13" value=3 />良好</label>&nbsp;<label><input type=radio name="z13" value=2 />一般</label>&nbsp;<label><input type=radio name="z13" value=1 />较差</label>&nbsp;<label><input type=radio name="z13" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>14、市信访局</b></p></td><td><p class=select><label><input type=radio name="z14" value=4 />优秀</label>&nbsp;<label><input type=radio name="z14" value=3 />良好</label>&nbsp;<label><input type=radio name="z14" value=2 />一般</label>&nbsp;<label><input type=radio name="z14" value=1 />较差</label>&nbsp;<label><input type=radio name="z14" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>15、市委老干部局</b></p></td><td><p class=select><label><input type=radio name="z15" value=4 />优秀</label>&nbsp;<label><input type=radio name="z15" value=3 />良好</label>&nbsp;<label><input type=radio name="z15" value=2 />一般</label>&nbsp;<label><input type=radio name="z15" value=1 />较差</label>&nbsp;<label><input type=radio name="z15" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>16、市委党史研究室</b></p></td><td><p class=select><label><input type=radio name="z16" value=4 />优秀</label>&nbsp;<label><input type=radio name="z16" value=3 />良好</label>&nbsp;<label><input type=radio name="z16" value=2 />一般</label>&nbsp;<label><input type=radio name="z16" value=1 />较差</label>&nbsp;<label><input type=radio name="z16" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>17、市委党校</b></p></td><td><p class=select><label><input type=radio name="z17" value=4 />优秀</label>&nbsp;<label><input type=radio name="z17" value=3 />良好</label>&nbsp;<label><input type=radio name="z17" value=2 />一般</label>&nbsp;<label><input type=radio name="z17" value=1 />较差</label>&nbsp;<label><input type=radio name="z17" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>18、市接待办</b></p></td><td><p class=select><label><input type=radio name="z18" value=4 />优秀</label>&nbsp;<label><input type=radio name="z18" value=3 />良好</label>&nbsp;<label><input type=radio name="z18" value=2 />一般</label>&nbsp;<label><input type=radio name="z18" value=1 />较差</label>&nbsp;<label><input type=radio name="z18" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>19、市总工会</b></p></td><td><p class=select><label><input type=radio name="z19" value=4 />优秀</label>&nbsp;<label><input type=radio name="z19" value=3 />良好</label>&nbsp;<label><input type=radio name="z19" value=2 />一般</label>&nbsp;<label><input type=radio name="z19" value=1 />较差</label>&nbsp;<label><input type=radio name="z19" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>20、团市委</b></p></td><td><p class=select><label><input type=radio name="z20" value=4 />优秀</label>&nbsp;<label><input type=radio name="z20" value=3 />良好</label>&nbsp;<label><input type=radio name="z20" value=2 />一般</label>&nbsp;<label><input type=radio name="z20" value=1 />较差</label>&nbsp;<label><input type=radio name="z20" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>21、市妇联</b></p></td><td><p class=select><label><input type=radio name="z21" value=4 />优秀</label>&nbsp;<label><input type=radio name="z21" value=3 />良好</label>&nbsp;<label><input type=radio name="z21" value=2 />一般</label>&nbsp;<label><input type=radio name="z21" value=1 />较差</label>&nbsp;<label><input type=radio name="z21" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>22、市文联</b></p></td><td><p class=select><label><input type=radio name="z22" value=4 />优秀</label>&nbsp;<label><input type=radio name="z22" value=3 />良好</label>&nbsp;<label><input type=radio name="z22" value=2 />一般</label>&nbsp;<label><input type=radio name="z22" value=1 />较差</label>&nbsp;<label><input type=radio name="z22" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>23、市工商联</b></p></td><td><p class=select><label><input type=radio name="z23" value=4 />优秀</label>&nbsp;<label><input type=radio name="z23" value=3 />良好</label>&nbsp;<label><input type=radio name="z23" value=2 />一般</label>&nbsp;<label><input type=radio name="z23" value=1 />较差</label>&nbsp;<label><input type=radio name="z23" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>24、市科协</b></p></td><td><p class=select><label><input type=radio name="z24" value=4 />优秀</label>&nbsp;<label><input type=radio name="z24" value=3 />良好</label>&nbsp;<label><input type=radio name="z24" value=2 />一般</label>&nbsp;<label><input type=radio name="z24" value=1 />较差</label>&nbsp;<label><input type=radio name="z24" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>25、市残联</b></p></td><td><p class=select><label><input type=radio name="z25" value=4 />优秀</label>&nbsp;<label><input type=radio name="z25" value=3 />良好</label>&nbsp;<label><input type=radio name="z25" value=2 />一般</label>&nbsp;<label><input type=radio name="z25" value=1 />较差</label>&nbsp;<label><input type=radio name="z25" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>26、市贸促会</b></p></td><td><p class=select><label><input type=radio name="z26" value=4 />优秀</label>&nbsp;<label><input type=radio name="z26" value=3 />良好</label>&nbsp;<label><input type=radio name="z26" value=2 />一般</label>&nbsp;<label><input type=radio name="z26" value=1 />较差</label>&nbsp;<label><input type=radio name="z26" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>27、市经济研究中心</b></p></td><td><p class=select><label><input type=radio name="z27" value=4 />优秀</label>&nbsp;<label><input type=radio name="z27" value=3 />良好</label>&nbsp;<label><input type=radio name="z27" value=2 />一般</label>&nbsp;<label><input type=radio name="z27" value=1 />较差</label>&nbsp;<label><input type=radio name="z27" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>28、市档案局</b></p></td><td><p class=select><label><input type=radio name="z28" value=4 />优秀</label>&nbsp;<label><input type=radio name="z28" value=3 />良好</label>&nbsp;<label><input type=radio name="z28" value=2 />一般</label>&nbsp;<label><input type=radio name="z28" value=1 />较差</label>&nbsp;<label><input type=radio name="z28" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>29、市发改委</b></p></td><td><p class=select><label><input type=radio name="z29" value=4 />优秀</label>&nbsp;<label><input type=radio name="z29" value=3 />良好</label>&nbsp;<label><input type=radio name="z29" value=2 />一般</label>&nbsp;<label><input type=radio name="z29" value=1 />较差</label>&nbsp;<label><input type=radio name="z29" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>30、市科技局</b></p></td><td><p class=select><label><input type=radio name="z30" value=4 />优秀</label>&nbsp;<label><input type=radio name="z30" value=3 />良好</label>&nbsp;<label><input type=radio name="z30" value=2 />一般</label>&nbsp;<label><input type=radio name="z30" value=1 />较差</label>&nbsp;<label><input type=radio name="z30" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>31、市工信局</b></p></td><td><p class=select><label><input type=radio name="z31" value=4 />优秀</label>&nbsp;<label><input type=radio name="z31" value=3 />良好</label>&nbsp;<label><input type=radio name="z31" value=2 />一般</label>&nbsp;<label><input type=radio name="z31" value=1 />较差</label>&nbsp;<label><input type=radio name="z31" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>32、市财政局</b></p></td><td><p class=select><label><input type=radio name="z32" value=4 />优秀</label>&nbsp;<label><input type=radio name="z32" value=3 />良好</label>&nbsp;<label><input type=radio name="z32" value=2 />一般</label>&nbsp;<label><input type=radio name="z32" value=1 />较差</label>&nbsp;<label><input type=radio name="z32" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>33、市农开办</b></p></td><td><p class=select><label><input type=radio name="z33" value=4 />优秀</label>&nbsp;<label><input type=radio name="z33" value=3 />良好</label>&nbsp;<label><input type=radio name="z33" value=2 />一般</label>&nbsp;<label><input type=radio name="z33" value=1 />较差</label>&nbsp;<label><input type=radio name="z33" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>34、市交通局</b></p></td><td><p class=select><label><input type=radio name="z34" value=4 />优秀</label>&nbsp;<label><input type=radio name="z34" value=3 />良好</label>&nbsp;<label><input type=radio name="z34" value=2 />一般</label>&nbsp;<label><input type=radio name="z34" value=1 />较差</label>&nbsp;<label><input type=radio name="z34" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>35、市水务局</b></p></td><td><p class=select><label><input type=radio name="z35" value=4 />优秀</label>&nbsp;<label><input type=radio name="z35" value=3 />良好</label>&nbsp;<label><input type=radio name="z35" value=2 />一般</label>&nbsp;<label><input type=radio name="z35" value=1 />较差</label>&nbsp;<label><input type=radio name="z35" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>36、市农业局</b></p></td><td><p class=select><label><input type=radio name="z36" value=4 />优秀</label>&nbsp;<label><input type=radio name="z36" value=3 />良好</label>&nbsp;<label><input type=radio name="z36" value=2 />一般</label>&nbsp;<label><input type=radio name="z36" value=1 />较差</label>&nbsp;<label><input type=radio name="z36" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>37、市林业局</b></p></td><td><p class=select><label><input type=radio name="z37" value=4 />优秀</label>&nbsp;<label><input type=radio name="z37" value=3 />良好</label>&nbsp;<label><input type=radio name="z37" value=2 />一般</label>&nbsp;<label><input type=radio name="z37" value=1 />较差</label>&nbsp;<label><input type=radio name="z37" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>38、市商务局</b></p></td><td><p class=select><label><input type=radio name="z38" value=4 />优秀</label>&nbsp;<label><input type=radio name="z38" value=3 />良好</label>&nbsp;<label><input type=radio name="z38" value=2 />一般</label>&nbsp;<label><input type=radio name="z38" value=1 />较差</label>&nbsp;<label><input type=radio name="z38" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>39、市国资委</b></p></td><td><p class=select><label><input type=radio name="z39" value=4 />优秀</label>&nbsp;<label><input type=radio name="z39" value=3 />良好</label>&nbsp;<label><input type=radio name="z39" value=2 />一般</label>&nbsp;<label><input type=radio name="z39" value=1 />较差</label>&nbsp;<label><input type=radio name="z39" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>40、市统计局</b></p></td><td><p class=select><label><input type=radio name="z40" value=4 />优秀</label>&nbsp;<label><input type=radio name="z40" value=3 />良好</label>&nbsp;<label><input type=radio name="z40" value=2 />一般</label>&nbsp;<label><input type=radio name="z40" value=1 />较差</label>&nbsp;<label><input type=radio name="z40" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>41、市旅游局</b></p></td><td><p class=select><label><input type=radio name="z41" value=4 />优秀</label>&nbsp;<label><input type=radio name="z41" value=3 />良好</label>&nbsp;<label><input type=radio name="z41" value=2 />一般</label>&nbsp;<label><input type=radio name="z41" value=1 />较差</label>&nbsp;<label><input type=radio name="z41" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>42、市供销社</b></p></td><td><p class=select><label><input type=radio name="z42" value=4 />优秀</label>&nbsp;<label><input type=radio name="z42" value=3 />良好</label>&nbsp;<label><input type=radio name="z42" value=2 />一般</label>&nbsp;<label><input type=radio name="z42" value=1 />较差</label>&nbsp;<label><input type=radio name="z42" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>43、统筹办</b></p></td><td><p class=select><label><input type=radio name="z43" value=4 />优秀</label>&nbsp;<label><input type=radio name="z43" value=3 />良好</label>&nbsp;<label><input type=radio name="z43" value=2 />一般</label>&nbsp;<label><input type=radio name="z43" value=1 />较差</label>&nbsp;<label><input type=radio name="z43" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>44、市中级人民法院</b></p></td><td><p class=select><label><input type=radio name="z44" value=4 />优秀</label>&nbsp;<label><input type=radio name="z44" value=3 />良好</label>&nbsp;<label><input type=radio name="z44" value=2 />一般</label>&nbsp;<label><input type=radio name="z44" value=1 />较差</label>&nbsp;<label><input type=radio name="z44" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>45、市人民检察院</b></p></td><td><p class=select><label><input type=radio name="z45" value=4 />优秀</label>&nbsp;<label><input type=radio name="z45" value=3 />良好</label>&nbsp;<label><input type=radio name="z45" value=2 />一般</label>&nbsp;<label><input type=radio name="z45" value=1 />较差</label>&nbsp;<label><input type=radio name="z45" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>46、市公安局</b></p></td><td><p class=select><label><input type=radio name="z46" value=4 />优秀</label>&nbsp;<label><input type=radio name="z46" value=3 />良好</label>&nbsp;<label><input type=radio name="z46" value=2 />一般</label>&nbsp;<label><input type=radio name="z46" value=1 />较差</label>&nbsp;<label><input type=radio name="z46" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>47、市司法局</b></p></td><td><p class=select><label><input type=radio name="z47" value=4 />优秀</label>&nbsp;<label><input type=radio name="z47" value=3 />良好</label>&nbsp;<label><input type=radio name="z47" value=2 />一般</label>&nbsp;<label><input type=radio name="z47" value=1 />较差</label>&nbsp;<label><input type=radio name="z47" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>48、市环保局</b></p></td><td><p class=select><label><input type=radio name="z48" value=4 />优秀</label>&nbsp;<label><input type=radio name="z48" value=3 />良好</label>&nbsp;<label><input type=radio name="z48" value=2 />一般</label>&nbsp;<label><input type=radio name="z48" value=1 />较差</label>&nbsp;<label><input type=radio name="z48" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>49、市房管局</b></p></td><td><p class=select><label><input type=radio name="z49" value=4 />优秀</label>&nbsp;<label><input type=radio name="z49" value=3 />良好</label>&nbsp;<label><input type=radio name="z49" value=2 />一般</label>&nbsp;<label><input type=radio name="z49" value=1 />较差</label>&nbsp;<label><input type=radio name="z49" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>50、市审计局</b></p></td><td><p class=select><label><input type=radio name="z50" value=4 />优秀</label>&nbsp;<label><input type=radio name="z50" value=3 />良好</label>&nbsp;<label><input type=radio name="z50" value=2 />一般</label>&nbsp;<label><input type=radio name="z50" value=1 />较差</label>&nbsp;<label><input type=radio name="z50" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>51、市安监局</b></p></td><td><p class=select><label><input type=radio name="z51" value=4 />优秀</label>&nbsp;<label><input type=radio name="z51" value=3 />良好</label>&nbsp;<label><input type=radio name="z51" value=2 />一般</label>&nbsp;<label><input type=radio name="z51" value=1 />较差</label>&nbsp;<label><input type=radio name="z51" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>52、市药监局</b></p></td><td><p class=select><label><input type=radio name="z52" value=4 />优秀</label>&nbsp;<label><input type=radio name="z52" value=3 />良好</label>&nbsp;<label><input type=radio name="z52" value=2 />一般</label>&nbsp;<label><input type=radio name="z52" value=1 />较差</label>&nbsp;<label><input type=radio name="z52" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>53、市物价局</b></p></td><td><p class=select><label><input type=radio name="z53" value=4 />优秀</label>&nbsp;<label><input type=radio name="z53" value=3 />良好</label>&nbsp;<label><input type=radio name="z53" value=2 />一般</label>&nbsp;<label><input type=radio name="z53" value=1 />较差</label>&nbsp;<label><input type=radio name="z53" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>54、市建设局</b></p></td><td><p class=select><label><input type=radio name="z54" value=4 />优秀</label>&nbsp;<label><input type=radio name="z54" value=3 />良好</label>&nbsp;<label><input type=radio name="z54" value=2 />一般</label>&nbsp;<label><input type=radio name="z54" value=1 />较差</label>&nbsp;<label><input type=radio name="z54" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>55、市城乡规划局</b></p></td><td><p class=select><label><input type=radio name="z55" value=4 />优秀</label>&nbsp;<label><input type=radio name="z55" value=3 />良好</label>&nbsp;<label><input type=radio name="z55" value=2 />一般</label>&nbsp;<label><input type=radio name="z55" value=1 />较差</label>&nbsp;<label><input type=radio name="z55" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>56、市综合执法局</b></p></td><td><p class=select><label><input type=radio name="z56" value=4 />优秀</label>&nbsp;<label><input type=radio name="z56" value=3 />良好</label>&nbsp;<label><input type=radio name="z56" value=2 />一般</label>&nbsp;<label><input type=radio name="z56" value=1 />较差</label>&nbsp;<label><input type=radio name="z56" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>57、市工商局</b></p></td><td><p class=select><label><input type=radio name="z57" value=4 />优秀</label>&nbsp;<label><input type=radio name="z57" value=3 />良好</label>&nbsp;<label><input type=radio name="z57" value=2 />一般</label>&nbsp;<label><input type=radio name="z57" value=1 />较差</label>&nbsp;<label><input type=radio name="z57" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>58、市质监局</b></p></td><td><p class=select><label><input type=radio name="z58" value=4 />优秀</label>&nbsp;<label><input type=radio name="z58" value=3 />良好</label>&nbsp;<label><input type=radio name="z58" value=2 />一般</label>&nbsp;<label><input type=radio name="z58" value=1 />较差</label>&nbsp;<label><input type=radio name="z58" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>59、市教育局</b></p></td><td><p class=select><label><input type=radio name="z59" value=4 />优秀</label>&nbsp;<label><input type=radio name="z59" value=3 />良好</label>&nbsp;<label><input type=radio name="z59" value=2 />一般</label>&nbsp;<label><input type=radio name="z59" value=1 />较差</label>&nbsp;<label><input type=radio name="z59" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>60、市民宗局</b></p></td><td><p class=select><label><input type=radio name="z60" value=4 />优秀</label>&nbsp;<label><input type=radio name="z60" value=3 />良好</label>&nbsp;<label><input type=radio name="z60" value=2 />一般</label>&nbsp;<label><input type=radio name="z60" value=1 />较差</label>&nbsp;<label><input type=radio name="z60" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>61、市民政局</b></p></td><td><p class=select><label><input type=radio name="z61" value=4 />优秀</label>&nbsp;<label><input type=radio name="z61" value=3 />良好</label>&nbsp;<label><input type=radio name="z61" value=2 />一般</label>&nbsp;<label><input type=radio name="z61" value=1 />较差</label>&nbsp;<label><input type=radio name="z61" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>62、市人社局</b></p></td><td><p class=select><label><input type=radio name="z62" value=4 />优秀</label>&nbsp;<label><input type=radio name="z62" value=3 />良好</label>&nbsp;<label><input type=radio name="z62" value=2 />一般</label>&nbsp;<label><input type=radio name="z62" value=1 />较差</label>&nbsp;<label><input type=radio name="z62" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>63、市文广新局</b></p></td><td><p class=select><label><input type=radio name="z63" value=4 />优秀</label>&nbsp;<label><input type=radio name="z63" value=3 />良好</label>&nbsp;<label><input type=radio name="z63" value=2 />一般</label>&nbsp;<label><input type=radio name="z63" value=1 />较差</label>&nbsp;<label><input type=radio name="z63" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>64、市卫计委</b></p></td><td><p class=select><label><input type=radio name="z64" value=4 />优秀</label>&nbsp;<label><input type=radio name="z64" value=3 />良好</label>&nbsp;<label><input type=radio name="z64" value=2 />一般</label>&nbsp;<label><input type=radio name="z64" value=1 />较差</label>&nbsp;<label><input type=radio name="z64" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>65、市体育局</b></p></td><td><p class=select><label><input type=radio name="z65" value=4 />优秀</label>&nbsp;<label><input type=radio name="z65" value=3 />良好</label>&nbsp;<label><input type=radio name="z65" value=2 />一般</label>&nbsp;<label><input type=radio name="z65" value=1 />较差</label>&nbsp;<label><input type=radio name="z65" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>66、市粮食局</b></p></td><td><p class=select><label><input type=radio name="z66" value=4 />优秀</label>&nbsp;<label><input type=radio name="z66" value=3 />良好</label>&nbsp;<label><input type=radio name="z66" value=2 />一般</label>&nbsp;<label><input type=radio name="z66" value=1 />较差</label>&nbsp;<label><input type=radio name="z66" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>67、市外事办</b></p></td><td><p class=select><label><input type=radio name="z67" value=4 />优秀</label>&nbsp;<label><input type=radio name="z67" value=3 />良好</label>&nbsp;<label><input type=radio name="z67" value=2 />一般</label>&nbsp;<label><input type=radio name="z67" value=1 />较差</label>&nbsp;<label><input type=radio name="z67" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>68、市地震局</b></p></td><td><p class=select><label><input type=radio name="z68" value=4 />优秀</label>&nbsp;<label><input type=radio name="z68" value=3 />良好</label>&nbsp;<label><input type=radio name="z68" value=2 />一般</label>&nbsp;<label><input type=radio name="z68" value=1 />较差</label>&nbsp;<label><input type=radio name="z68" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>69、市住房公积金</b></p></td><td><p class=select><label><input type=radio name="z69" value=4 />优秀</label>&nbsp;<label><input type=radio name="z69" value=3 />良好</label>&nbsp;<label><input type=radio name="z69" value=2 />一般</label>&nbsp;<label><input type=radio name="z69" value=1 />较差</label>&nbsp;<label><input type=radio name="z69" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>70、步行街管委会</b></p></td><td><p class=select><label><input type=radio name="z70" value=4 />优秀</label>&nbsp;<label><input type=radio name="z70" value=3 />良好</label>&nbsp;<label><input type=radio name="z70" value=2 />一般</label>&nbsp;<label><input type=radio name="z70" value=1 />较差</label>&nbsp;<label><input type=radio name="z70" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>71、市机场办</b></p></td><td><p class=select><label><input type=radio name="z71" value=4 />优秀</label>&nbsp;<label><input type=radio name="z71" value=3 />良好</label>&nbsp;<label><input type=radio name="z71" value=2 />一般</label>&nbsp;<label><input type=radio name="z71" value=1 />较差</label>&nbsp;<label><input type=radio name="z71" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>72、市政务办</b></p></td><td><p class=select><label><input type=radio name="z72" value=4 />优秀</label>&nbsp;<label><input type=radio name="z72" value=3 />良好</label>&nbsp;<label><input type=radio name="z72" value=2 />一般</label>&nbsp;<label><input type=radio name="z72" value=1 />较差</label>&nbsp;<label><input type=radio name="z72" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>73、廊坊日报社</b></p></td><td><p class=select><label><input type=radio name="z73" value=4 />优秀</label>&nbsp;<label><input type=radio name="z73" value=3 />良好</label>&nbsp;<label><input type=radio name="z73" value=2 />一般</label>&nbsp;<label><input type=radio name="z73" value=1 />较差</label>&nbsp;<label><input type=radio name="z73" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>74、廊坊广播电视台</b></p></td><td><p class=select><label><input type=radio name="z74" value=4 />优秀</label>&nbsp;<label><input type=radio name="z74" value=3 />良好</label>&nbsp;<label><input type=radio name="z74" value=2 />一般</label>&nbsp;<label><input type=radio name="z74" value=1 />较差</label>&nbsp;<label><input type=radio name="z74" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>75、廊坊职技学院</b></p></td><td><p class=select><label><input type=radio name="z75" value=4 />优秀</label>&nbsp;<label><input type=radio name="z75" value=3 />良好</label>&nbsp;<label><input type=radio name="z75" value=2 />一般</label>&nbsp;<label><input type=radio name="z75" value=1 />较差</label>&nbsp;<label><input type=radio name="z75" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>76、燕京职技学院</b></p></td><td><p class=select><label><input type=radio name="z76" value=4 />优秀</label>&nbsp;<label><input type=radio name="z76" value=3 />良好</label>&nbsp;<label><input type=radio name="z76" value=2 />一般</label>&nbsp;<label><input type=radio name="z76" value=1 />较差</label>&nbsp;<label><input type=radio name="z76" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>77、廊坊卫生学院</b></p></td><td><p class=select><label><input type=radio name="z77" value=4 />优秀</label>&nbsp;<label><input type=radio name="z77" value=3 />良好</label>&nbsp;<label><input type=radio name="z77" value=2 />一般</label>&nbsp;<label><input type=radio name="z77" value=1 />较差</label>&nbsp;<label><input type=radio name="z77" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>78、市电子信息学校</b></p></td><td><p class=select><label><input type=radio name="z78" value=4 />优秀</label>&nbsp;<label><input type=radio name="z78" value=3 />良好</label>&nbsp;<label><input type=radio name="z78" value=2 />一般</label>&nbsp;<label><input type=radio name="z78" value=1 />较差</label>&nbsp;<label><input type=radio name="z78" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>79、市电大</b></p></td><td><p class=select><label><input type=radio name="z79" value=4 />优秀</label>&nbsp;<label><input type=radio name="z79" value=3 />良好</label>&nbsp;<label><input type=radio name="z79" value=2 />一般</label>&nbsp;<label><input type=radio name="z79" value=1 />较差</label>&nbsp;<label><input type=radio name="z79" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>80、市高级技工学校</b></p></td><td><p class=select><label><input type=radio name="z80" value=4 />优秀</label>&nbsp;<label><input type=radio name="z80" value=3 />良好</label>&nbsp;<label><input type=radio name="z80" value=2 />一般</label>&nbsp;<label><input type=radio name="z80" value=1 />较差</label>&nbsp;<label><input type=radio name="z80" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>81、市体校</b></p></td><td><p class=select><label><input type=radio name="z81" value=4 />优秀</label>&nbsp;<label><input type=radio name="z81" value=3 />良好</label>&nbsp;<label><input type=radio name="z81" value=2 />一般</label>&nbsp;<label><input type=radio name="z81" value=1 />较差</label>&nbsp;<label><input type=radio name="z81" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>82、市农科院</b></p></td><td><p class=select><label><input type=radio name="z82" value=4 />优秀</label>&nbsp;<label><input type=radio name="z82" value=3 />良好</label>&nbsp;<label><input type=radio name="z82" value=2 />一般</label>&nbsp;<label><input type=radio name="z82" value=1 />较差</label>&nbsp;<label><input type=radio name="z82" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>83、市医院</b></p></td><td><p class=select><label><input type=radio name="z83" value=4 />优秀</label>&nbsp;<label><input type=radio name="z83" value=3 />良好</label>&nbsp;<label><input type=radio name="z83" value=2 />一般</label>&nbsp;<label><input type=radio name="z83" value=1 />较差</label>&nbsp;<label><input type=radio name="z83" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>84、市中医院</b></p></td><td><p class=select><label><input type=radio name="z84" value=4 />优秀</label>&nbsp;<label><input type=radio name="z84" value=3 />良好</label>&nbsp;<label><input type=radio name="z84" value=2 />一般</label>&nbsp;<label><input type=radio name="z84" value=1 />较差</label>&nbsp;<label><input type=radio name="z84" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>85、市第三医院</b></p></td><td><p class=select><label><input type=radio name="z85" value=4 />优秀</label>&nbsp;<label><input type=radio name="z85" value=3 />良好</label>&nbsp;<label><input type=radio name="z85" value=2 />一般</label>&nbsp;<label><input type=radio name="z85" value=1 />较差</label>&nbsp;<label><input type=radio name="z85" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>86、市一中</b></p></td><td><p class=select><label><input type=radio name="z86" value=4 />优秀</label>&nbsp;<label><input type=radio name="z86" value=3 />良好</label>&nbsp;<label><input type=radio name="z86" value=2 />一般</label>&nbsp;<label><input type=radio name="z86" value=1 />较差</label>&nbsp;<label><input type=radio name="z86" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>87、管道局中学</b></p></td><td><p class=select><label><input type=radio name="z87" value=4 />优秀</label>&nbsp;<label><input type=radio name="z87" value=3 />良好</label>&nbsp;<label><input type=radio name="z87" value=2 />一般</label>&nbsp;<label><input type=radio name="z87" value=1 />较差</label>&nbsp;<label><input type=radio name="z87" value=0 checked />不了解</label>&nbsp;</p></td></tr>

			</table>
				
			<p class=sub_title><b>二、具体评价。对所列评价单位领导班子和市委管理干部提出的意见和建议。</b></p>
			<p class=txt><textarea name=suggest id=suggesttext placeholder="请输入您的意见！" onpropertychange="checkMaxLen(this,2000);" oninput="checkMaxLen(this,2000);"></textarea></p>
			<br>
			<input type=hidden name=step value=questionz />
			<div class=center><input class=btn type="submit" value="提交问卷" /></div>
		</form>
	</div>
</body>
</html>