<?php
/* Smarty version 3.1.29, created on 2016-02-23 10:17:02
  from "C:\Users\Kinzo\git\php\vote\v3\templates\questionz.html" */

if ($_smarty_tpl->smarty->ext->_validateCompiled->decodeProperties($_smarty_tpl, array (
  'has_nocache_code' => false,
  'version' => '3.1.29',
  'unifunc' => 'content_56cbc11e67a448_45786123',
  'file_dependency' => 
  array (
    '70365fc6e68d3b992700a6a60694a151d3569b5b' => 
    array (
      0 => 'C:\\Users\\Kinzo\\git\\php\\vote\\v3\\templates\\questionz.html',
      1 => 1456104787,
      2 => 'file',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_56cbc11e67a448_45786123 ($_smarty_tpl) {
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>廊坊市干部考核社会评价调查系统</title>
	<link href="./css/main.css" type="text/css" rel="stylesheet">
	<?php echo '<script'; ?>
 type="text/javascript" src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.min.js"><?php echo '</script'; ?>
>
</head>
<body bgcolor=white lang=ZH-CN>
	<p class=title align=center>
		市直单位领导班子评价
	</p>

	<div class=main>
		<form id="user_login" action="" method="post">

			<p class=sub_title><b>一、总体评价。请对所列单位领导班子进行评价，如不选择默认为不了解。</b></p>
			<table>
				<tr><td><p class=txt><b class=blue>1、市纪委（监察局）</b></p></td><td><p class=select><label><input type=radio name="z01" value=4/>优秀</label>&nbsp;<label><input type=radio name="z01" value=3/>良好</label>&nbsp;<label><input type=radio name="z01" value=2/>一般</label>&nbsp;<label><input type=radio name="z01" value=1/>较差</label>&nbsp;<label><input type=radio name="z01" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>2、市委办公室</b></p></td><td><p class=select><label><input type=radio name="z02" value=4/>优秀</label>&nbsp;<label><input type=radio name="z02" value=3/>良好</label>&nbsp;<label><input type=radio name="z02" value=2/>一般</label>&nbsp;<label><input type=radio name="z02" value=1/>较差</label>&nbsp;<label><input type=radio name="z02" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>3、市政府办公室</b></p></td><td><p class=select><label><input type=radio name="z03" value=4/>优秀</label>&nbsp;<label><input type=radio name="z03" value=3/>良好</label>&nbsp;<label><input type=radio name="z03" value=2/>一般</label>&nbsp;<label><input type=radio name="z03" value=1/>较差</label>&nbsp;<label><input type=radio name="z03" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>4、市人大机关</b></p></td><td><p class=select><label><input type=radio name="z04" value=4/>优秀</label>&nbsp;<label><input type=radio name="z04" value=3/>良好</label>&nbsp;<label><input type=radio name="z04" value=2/>一般</label>&nbsp;<label><input type=radio name="z04" value=1/>较差</label>&nbsp;<label><input type=radio name="z04" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>5、市政协机关</b></p></td><td><p class=select><label><input type=radio name="z05" value=4/>优秀</label>&nbsp;<label><input type=radio name="z05" value=3/>良好</label>&nbsp;<label><input type=radio name="z05" value=2/>一般</label>&nbsp;<label><input type=radio name="z05" value=1/>较差</label>&nbsp;<label><input type=radio name="z05" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>6、市委组织部</b></p></td><td><p class=select><label><input type=radio name="z06" value=4/>优秀</label>&nbsp;<label><input type=radio name="z06" value=3/>良好</label>&nbsp;<label><input type=radio name="z06" value=2/>一般</label>&nbsp;<label><input type=radio name="z06" value=1/>较差</label>&nbsp;<label><input type=radio name="z06" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>7、市委宣传部</b></p></td><td><p class=select><label><input type=radio name="z07" value=4/>优秀</label>&nbsp;<label><input type=radio name="z07" value=3/>良好</label>&nbsp;<label><input type=radio name="z07" value=2/>一般</label>&nbsp;<label><input type=radio name="z07" value=1/>较差</label>&nbsp;<label><input type=radio name="z07" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>8、市委统战部</b></p></td><td><p class=select><label><input type=radio name="z08" value=4/>优秀</label>&nbsp;<label><input type=radio name="z08" value=3/>良好</label>&nbsp;<label><input type=radio name="z08" value=2/>一般</label>&nbsp;<label><input type=radio name="z08" value=1/>较差</label>&nbsp;<label><input type=radio name="z08" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>9、市委农工部</b></p></td><td><p class=select><label><input type=radio name="z09" value=4/>优秀</label>&nbsp;<label><input type=radio name="z09" value=3/>良好</label>&nbsp;<label><input type=radio name="z09" value=2/>一般</label>&nbsp;<label><input type=radio name="z09" value=1/>较差</label>&nbsp;<label><input type=radio name="z09" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>10、市委政法委</b></p></td><td><p class=select><label><input type=radio name="z10" value=4/>优秀</label>&nbsp;<label><input type=radio name="z10" value=3/>良好</label>&nbsp;<label><input type=radio name="z10" value=2/>一般</label>&nbsp;<label><input type=radio name="z10" value=1/>较差</label>&nbsp;<label><input type=radio name="z10" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>11、市委研究室</b></p></td><td><p class=select><label><input type=radio name="z11" value=4/>优秀</label>&nbsp;<label><input type=radio name="z11" value=3/>良好</label>&nbsp;<label><input type=radio name="z11" value=2/>一般</label>&nbsp;<label><input type=radio name="z11" value=1/>较差</label>&nbsp;<label><input type=radio name="z11" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>12、市直工委</b></p></td><td><p class=select><label><input type=radio name="z12" value=4/>优秀</label>&nbsp;<label><input type=radio name="z12" value=3/>良好</label>&nbsp;<label><input type=radio name="z12" value=2/>一般</label>&nbsp;<label><input type=radio name="z12" value=1/>较差</label>&nbsp;<label><input type=radio name="z12" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>13、市编办</b></p></td><td><p class=select><label><input type=radio name="z13" value=4/>优秀</label>&nbsp;<label><input type=radio name="z13" value=3/>良好</label>&nbsp;<label><input type=radio name="z13" value=2/>一般</label>&nbsp;<label><input type=radio name="z13" value=1/>较差</label>&nbsp;<label><input type=radio name="z13" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>14、市信访局</b></p></td><td><p class=select><label><input type=radio name="z14" value=4/>优秀</label>&nbsp;<label><input type=radio name="z14" value=3/>良好</label>&nbsp;<label><input type=radio name="z14" value=2/>一般</label>&nbsp;<label><input type=radio name="z14" value=1/>较差</label>&nbsp;<label><input type=radio name="z14" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>15、市委老干部局</b></p></td><td><p class=select><label><input type=radio name="z15" value=4/>优秀</label>&nbsp;<label><input type=radio name="z15" value=3/>良好</label>&nbsp;<label><input type=radio name="z15" value=2/>一般</label>&nbsp;<label><input type=radio name="z15" value=1/>较差</label>&nbsp;<label><input type=radio name="z15" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>16、市委党史研究室</b></p></td><td><p class=select><label><input type=radio name="z16" value=4/>优秀</label>&nbsp;<label><input type=radio name="z16" value=3/>良好</label>&nbsp;<label><input type=radio name="z16" value=2/>一般</label>&nbsp;<label><input type=radio name="z16" value=1/>较差</label>&nbsp;<label><input type=radio name="z16" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>17、市委党校</b></p></td><td><p class=select><label><input type=radio name="z17" value=4/>优秀</label>&nbsp;<label><input type=radio name="z17" value=3/>良好</label>&nbsp;<label><input type=radio name="z17" value=2/>一般</label>&nbsp;<label><input type=radio name="z17" value=1/>较差</label>&nbsp;<label><input type=radio name="z17" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>18、市接待办</b></p></td><td><p class=select><label><input type=radio name="z18" value=4/>优秀</label>&nbsp;<label><input type=radio name="z18" value=3/>良好</label>&nbsp;<label><input type=radio name="z18" value=2/>一般</label>&nbsp;<label><input type=radio name="z18" value=1/>较差</label>&nbsp;<label><input type=radio name="z18" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>19、市总工会</b></p></td><td><p class=select><label><input type=radio name="z19" value=4/>优秀</label>&nbsp;<label><input type=radio name="z19" value=3/>良好</label>&nbsp;<label><input type=radio name="z19" value=2/>一般</label>&nbsp;<label><input type=radio name="z19" value=1/>较差</label>&nbsp;<label><input type=radio name="z19" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>20、团市委</b></p></td><td><p class=select><label><input type=radio name="z20" value=4/>优秀</label>&nbsp;<label><input type=radio name="z20" value=3/>良好</label>&nbsp;<label><input type=radio name="z20" value=2/>一般</label>&nbsp;<label><input type=radio name="z20" value=1/>较差</label>&nbsp;<label><input type=radio name="z20" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>21、市妇联</b></p></td><td><p class=select><label><input type=radio name="z21" value=4/>优秀</label>&nbsp;<label><input type=radio name="z21" value=3/>良好</label>&nbsp;<label><input type=radio name="z21" value=2/>一般</label>&nbsp;<label><input type=radio name="z21" value=1/>较差</label>&nbsp;<label><input type=radio name="z21" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>22、市文联</b></p></td><td><p class=select><label><input type=radio name="z22" value=4/>优秀</label>&nbsp;<label><input type=radio name="z22" value=3/>良好</label>&nbsp;<label><input type=radio name="z22" value=2/>一般</label>&nbsp;<label><input type=radio name="z22" value=1/>较差</label>&nbsp;<label><input type=radio name="z22" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>23、市工商联</b></p></td><td><p class=select><label><input type=radio name="z23" value=4/>优秀</label>&nbsp;<label><input type=radio name="z23" value=3/>良好</label>&nbsp;<label><input type=radio name="z23" value=2/>一般</label>&nbsp;<label><input type=radio name="z23" value=1/>较差</label>&nbsp;<label><input type=radio name="z23" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>24、市科协</b></p></td><td><p class=select><label><input type=radio name="z24" value=4/>优秀</label>&nbsp;<label><input type=radio name="z24" value=3/>良好</label>&nbsp;<label><input type=radio name="z24" value=2/>一般</label>&nbsp;<label><input type=radio name="z24" value=1/>较差</label>&nbsp;<label><input type=radio name="z24" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>25、市残联</b></p></td><td><p class=select><label><input type=radio name="z25" value=4/>优秀</label>&nbsp;<label><input type=radio name="z25" value=3/>良好</label>&nbsp;<label><input type=radio name="z25" value=2/>一般</label>&nbsp;<label><input type=radio name="z25" value=1/>较差</label>&nbsp;<label><input type=radio name="z25" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>26、市贸促会</b></p></td><td><p class=select><label><input type=radio name="z26" value=4/>优秀</label>&nbsp;<label><input type=radio name="z26" value=3/>良好</label>&nbsp;<label><input type=radio name="z26" value=2/>一般</label>&nbsp;<label><input type=radio name="z26" value=1/>较差</label>&nbsp;<label><input type=radio name="z26" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>27、市经济研究中心</b></p></td><td><p class=select><label><input type=radio name="z27" value=4/>优秀</label>&nbsp;<label><input type=radio name="z27" value=3/>良好</label>&nbsp;<label><input type=radio name="z27" value=2/>一般</label>&nbsp;<label><input type=radio name="z27" value=1/>较差</label>&nbsp;<label><input type=radio name="z27" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>28、市档案局</b></p></td><td><p class=select><label><input type=radio name="z28" value=4/>优秀</label>&nbsp;<label><input type=radio name="z28" value=3/>良好</label>&nbsp;<label><input type=radio name="z28" value=2/>一般</label>&nbsp;<label><input type=radio name="z28" value=1/>较差</label>&nbsp;<label><input type=radio name="z28" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>29、市发改委</b></p></td><td><p class=select><label><input type=radio name="z29" value=4/>优秀</label>&nbsp;<label><input type=radio name="z29" value=3/>良好</label>&nbsp;<label><input type=radio name="z29" value=2/>一般</label>&nbsp;<label><input type=radio name="z29" value=1/>较差</label>&nbsp;<label><input type=radio name="z29" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>30、市科技局</b></p></td><td><p class=select><label><input type=radio name="z30" value=4/>优秀</label>&nbsp;<label><input type=radio name="z30" value=3/>良好</label>&nbsp;<label><input type=radio name="z30" value=2/>一般</label>&nbsp;<label><input type=radio name="z30" value=1/>较差</label>&nbsp;<label><input type=radio name="z30" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>31、市工信局</b></p></td><td><p class=select><label><input type=radio name="z31" value=4/>优秀</label>&nbsp;<label><input type=radio name="z31" value=3/>良好</label>&nbsp;<label><input type=radio name="z31" value=2/>一般</label>&nbsp;<label><input type=radio name="z31" value=1/>较差</label>&nbsp;<label><input type=radio name="z31" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>32、市财政局</b></p></td><td><p class=select><label><input type=radio name="z32" value=4/>优秀</label>&nbsp;<label><input type=radio name="z32" value=3/>良好</label>&nbsp;<label><input type=radio name="z32" value=2/>一般</label>&nbsp;<label><input type=radio name="z32" value=1/>较差</label>&nbsp;<label><input type=radio name="z32" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>33、市农开办</b></p></td><td><p class=select><label><input type=radio name="z33" value=4/>优秀</label>&nbsp;<label><input type=radio name="z33" value=3/>良好</label>&nbsp;<label><input type=radio name="z33" value=2/>一般</label>&nbsp;<label><input type=radio name="z33" value=1/>较差</label>&nbsp;<label><input type=radio name="z33" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>34、市交通局</b></p></td><td><p class=select><label><input type=radio name="z34" value=4/>优秀</label>&nbsp;<label><input type=radio name="z34" value=3/>良好</label>&nbsp;<label><input type=radio name="z34" value=2/>一般</label>&nbsp;<label><input type=radio name="z34" value=1/>较差</label>&nbsp;<label><input type=radio name="z34" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>35、市水务局</b></p></td><td><p class=select><label><input type=radio name="z35" value=4/>优秀</label>&nbsp;<label><input type=radio name="z35" value=3/>良好</label>&nbsp;<label><input type=radio name="z35" value=2/>一般</label>&nbsp;<label><input type=radio name="z35" value=1/>较差</label>&nbsp;<label><input type=radio name="z35" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>36、市农业局</b></p></td><td><p class=select><label><input type=radio name="z36" value=4/>优秀</label>&nbsp;<label><input type=radio name="z36" value=3/>良好</label>&nbsp;<label><input type=radio name="z36" value=2/>一般</label>&nbsp;<label><input type=radio name="z36" value=1/>较差</label>&nbsp;<label><input type=radio name="z36" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>37、市林业局</b></p></td><td><p class=select><label><input type=radio name="z37" value=4/>优秀</label>&nbsp;<label><input type=radio name="z37" value=3/>良好</label>&nbsp;<label><input type=radio name="z37" value=2/>一般</label>&nbsp;<label><input type=radio name="z37" value=1/>较差</label>&nbsp;<label><input type=radio name="z37" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>38、市商务局</b></p></td><td><p class=select><label><input type=radio name="z38" value=4/>优秀</label>&nbsp;<label><input type=radio name="z38" value=3/>良好</label>&nbsp;<label><input type=radio name="z38" value=2/>一般</label>&nbsp;<label><input type=radio name="z38" value=1/>较差</label>&nbsp;<label><input type=radio name="z38" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>39、市国资委</b></p></td><td><p class=select><label><input type=radio name="z39" value=4/>优秀</label>&nbsp;<label><input type=radio name="z39" value=3/>良好</label>&nbsp;<label><input type=radio name="z39" value=2/>一般</label>&nbsp;<label><input type=radio name="z39" value=1/>较差</label>&nbsp;<label><input type=radio name="z39" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>40、市统计局</b></p></td><td><p class=select><label><input type=radio name="z40" value=4/>优秀</label>&nbsp;<label><input type=radio name="z40" value=3/>良好</label>&nbsp;<label><input type=radio name="z40" value=2/>一般</label>&nbsp;<label><input type=radio name="z40" value=1/>较差</label>&nbsp;<label><input type=radio name="z40" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>41、市旅游局</b></p></td><td><p class=select><label><input type=radio name="z41" value=4/>优秀</label>&nbsp;<label><input type=radio name="z41" value=3/>良好</label>&nbsp;<label><input type=radio name="z41" value=2/>一般</label>&nbsp;<label><input type=radio name="z41" value=1/>较差</label>&nbsp;<label><input type=radio name="z41" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>42、市供销社</b></p></td><td><p class=select><label><input type=radio name="z42" value=4/>优秀</label>&nbsp;<label><input type=radio name="z42" value=3/>良好</label>&nbsp;<label><input type=radio name="z42" value=2/>一般</label>&nbsp;<label><input type=radio name="z42" value=1/>较差</label>&nbsp;<label><input type=radio name="z42" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>43、统筹办</b></p></td><td><p class=select><label><input type=radio name="z43" value=4/>优秀</label>&nbsp;<label><input type=radio name="z43" value=3/>良好</label>&nbsp;<label><input type=radio name="z43" value=2/>一般</label>&nbsp;<label><input type=radio name="z43" value=1/>较差</label>&nbsp;<label><input type=radio name="z43" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>44、市中级人民法院</b></p></td><td><p class=select><label><input type=radio name="z44" value=4/>优秀</label>&nbsp;<label><input type=radio name="z44" value=3/>良好</label>&nbsp;<label><input type=radio name="z44" value=2/>一般</label>&nbsp;<label><input type=radio name="z44" value=1/>较差</label>&nbsp;<label><input type=radio name="z44" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>45、市人民检察院</b></p></td><td><p class=select><label><input type=radio name="z45" value=4/>优秀</label>&nbsp;<label><input type=radio name="z45" value=3/>良好</label>&nbsp;<label><input type=radio name="z45" value=2/>一般</label>&nbsp;<label><input type=radio name="z45" value=1/>较差</label>&nbsp;<label><input type=radio name="z45" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>46、市公安局</b></p></td><td><p class=select><label><input type=radio name="z46" value=4/>优秀</label>&nbsp;<label><input type=radio name="z46" value=3/>良好</label>&nbsp;<label><input type=radio name="z46" value=2/>一般</label>&nbsp;<label><input type=radio name="z46" value=1/>较差</label>&nbsp;<label><input type=radio name="z46" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>47、市司法局</b></p></td><td><p class=select><label><input type=radio name="z47" value=4/>优秀</label>&nbsp;<label><input type=radio name="z47" value=3/>良好</label>&nbsp;<label><input type=radio name="z47" value=2/>一般</label>&nbsp;<label><input type=radio name="z47" value=1/>较差</label>&nbsp;<label><input type=radio name="z47" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>48、市环保局</b></p></td><td><p class=select><label><input type=radio name="z48" value=4/>优秀</label>&nbsp;<label><input type=radio name="z48" value=3/>良好</label>&nbsp;<label><input type=radio name="z48" value=2/>一般</label>&nbsp;<label><input type=radio name="z48" value=1/>较差</label>&nbsp;<label><input type=radio name="z48" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>49、市房管局</b></p></td><td><p class=select><label><input type=radio name="z49" value=4/>优秀</label>&nbsp;<label><input type=radio name="z49" value=3/>良好</label>&nbsp;<label><input type=radio name="z49" value=2/>一般</label>&nbsp;<label><input type=radio name="z49" value=1/>较差</label>&nbsp;<label><input type=radio name="z49" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>50、市审计局</b></p></td><td><p class=select><label><input type=radio name="z50" value=4/>优秀</label>&nbsp;<label><input type=radio name="z50" value=3/>良好</label>&nbsp;<label><input type=radio name="z50" value=2/>一般</label>&nbsp;<label><input type=radio name="z50" value=1/>较差</label>&nbsp;<label><input type=radio name="z50" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>51、市安监局</b></p></td><td><p class=select><label><input type=radio name="z51" value=4/>优秀</label>&nbsp;<label><input type=radio name="z51" value=3/>良好</label>&nbsp;<label><input type=radio name="z51" value=2/>一般</label>&nbsp;<label><input type=radio name="z51" value=1/>较差</label>&nbsp;<label><input type=radio name="z51" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>52、市药监局</b></p></td><td><p class=select><label><input type=radio name="z52" value=4/>优秀</label>&nbsp;<label><input type=radio name="z52" value=3/>良好</label>&nbsp;<label><input type=radio name="z52" value=2/>一般</label>&nbsp;<label><input type=radio name="z52" value=1/>较差</label>&nbsp;<label><input type=radio name="z52" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>53、市物价局</b></p></td><td><p class=select><label><input type=radio name="z53" value=4/>优秀</label>&nbsp;<label><input type=radio name="z53" value=3/>良好</label>&nbsp;<label><input type=radio name="z53" value=2/>一般</label>&nbsp;<label><input type=radio name="z53" value=1/>较差</label>&nbsp;<label><input type=radio name="z53" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>54、市建设局</b></p></td><td><p class=select><label><input type=radio name="z54" value=4/>优秀</label>&nbsp;<label><input type=radio name="z54" value=3/>良好</label>&nbsp;<label><input type=radio name="z54" value=2/>一般</label>&nbsp;<label><input type=radio name="z54" value=1/>较差</label>&nbsp;<label><input type=radio name="z54" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>55、市城乡规划局</b></p></td><td><p class=select><label><input type=radio name="z55" value=4/>优秀</label>&nbsp;<label><input type=radio name="z55" value=3/>良好</label>&nbsp;<label><input type=radio name="z55" value=2/>一般</label>&nbsp;<label><input type=radio name="z55" value=1/>较差</label>&nbsp;<label><input type=radio name="z55" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>56、市综合执法局</b></p></td><td><p class=select><label><input type=radio name="z56" value=4/>优秀</label>&nbsp;<label><input type=radio name="z56" value=3/>良好</label>&nbsp;<label><input type=radio name="z56" value=2/>一般</label>&nbsp;<label><input type=radio name="z56" value=1/>较差</label>&nbsp;<label><input type=radio name="z56" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>57、市工商局</b></p></td><td><p class=select><label><input type=radio name="z57" value=4/>优秀</label>&nbsp;<label><input type=radio name="z57" value=3/>良好</label>&nbsp;<label><input type=radio name="z57" value=2/>一般</label>&nbsp;<label><input type=radio name="z57" value=1/>较差</label>&nbsp;<label><input type=radio name="z57" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>58、市质监局</b></p></td><td><p class=select><label><input type=radio name="z58" value=4/>优秀</label>&nbsp;<label><input type=radio name="z58" value=3/>良好</label>&nbsp;<label><input type=radio name="z58" value=2/>一般</label>&nbsp;<label><input type=radio name="z58" value=1/>较差</label>&nbsp;<label><input type=radio name="z58" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>59、市教育局</b></p></td><td><p class=select><label><input type=radio name="z59" value=4/>优秀</label>&nbsp;<label><input type=radio name="z59" value=3/>良好</label>&nbsp;<label><input type=radio name="z59" value=2/>一般</label>&nbsp;<label><input type=radio name="z59" value=1/>较差</label>&nbsp;<label><input type=radio name="z59" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>60、市民宗局</b></p></td><td><p class=select><label><input type=radio name="z60" value=4/>优秀</label>&nbsp;<label><input type=radio name="z60" value=3/>良好</label>&nbsp;<label><input type=radio name="z60" value=2/>一般</label>&nbsp;<label><input type=radio name="z60" value=1/>较差</label>&nbsp;<label><input type=radio name="z60" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>61、市民政局</b></p></td><td><p class=select><label><input type=radio name="z61" value=4/>优秀</label>&nbsp;<label><input type=radio name="z61" value=3/>良好</label>&nbsp;<label><input type=radio name="z61" value=2/>一般</label>&nbsp;<label><input type=radio name="z61" value=1/>较差</label>&nbsp;<label><input type=radio name="z61" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>62、市人社局</b></p></td><td><p class=select><label><input type=radio name="z62" value=4/>优秀</label>&nbsp;<label><input type=radio name="z62" value=3/>良好</label>&nbsp;<label><input type=radio name="z62" value=2/>一般</label>&nbsp;<label><input type=radio name="z62" value=1/>较差</label>&nbsp;<label><input type=radio name="z62" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>63、市文广新局</b></p></td><td><p class=select><label><input type=radio name="z63" value=4/>优秀</label>&nbsp;<label><input type=radio name="z63" value=3/>良好</label>&nbsp;<label><input type=radio name="z63" value=2/>一般</label>&nbsp;<label><input type=radio name="z63" value=1/>较差</label>&nbsp;<label><input type=radio name="z63" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>64、市卫计委</b></p></td><td><p class=select><label><input type=radio name="z64" value=4/>优秀</label>&nbsp;<label><input type=radio name="z64" value=3/>良好</label>&nbsp;<label><input type=radio name="z64" value=2/>一般</label>&nbsp;<label><input type=radio name="z64" value=1/>较差</label>&nbsp;<label><input type=radio name="z64" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>65、市体育局</b></p></td><td><p class=select><label><input type=radio name="z65" value=4/>优秀</label>&nbsp;<label><input type=radio name="z65" value=3/>良好</label>&nbsp;<label><input type=radio name="z65" value=2/>一般</label>&nbsp;<label><input type=radio name="z65" value=1/>较差</label>&nbsp;<label><input type=radio name="z65" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>66、市粮食局</b></p></td><td><p class=select><label><input type=radio name="z66" value=4/>优秀</label>&nbsp;<label><input type=radio name="z66" value=3/>良好</label>&nbsp;<label><input type=radio name="z66" value=2/>一般</label>&nbsp;<label><input type=radio name="z66" value=1/>较差</label>&nbsp;<label><input type=radio name="z66" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>67、市外事办</b></p></td><td><p class=select><label><input type=radio name="z67" value=4/>优秀</label>&nbsp;<label><input type=radio name="z67" value=3/>良好</label>&nbsp;<label><input type=radio name="z67" value=2/>一般</label>&nbsp;<label><input type=radio name="z67" value=1/>较差</label>&nbsp;<label><input type=radio name="z67" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>68、市地震局</b></p></td><td><p class=select><label><input type=radio name="z68" value=4/>优秀</label>&nbsp;<label><input type=radio name="z68" value=3/>良好</label>&nbsp;<label><input type=radio name="z68" value=2/>一般</label>&nbsp;<label><input type=radio name="z68" value=1/>较差</label>&nbsp;<label><input type=radio name="z68" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>69、市住房公积金</b></p></td><td><p class=select><label><input type=radio name="z69" value=4/>优秀</label>&nbsp;<label><input type=radio name="z69" value=3/>良好</label>&nbsp;<label><input type=radio name="z69" value=2/>一般</label>&nbsp;<label><input type=radio name="z69" value=1/>较差</label>&nbsp;<label><input type=radio name="z69" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>70、步行街管委会</b></p></td><td><p class=select><label><input type=radio name="z70" value=4/>优秀</label>&nbsp;<label><input type=radio name="z70" value=3/>良好</label>&nbsp;<label><input type=radio name="z70" value=2/>一般</label>&nbsp;<label><input type=radio name="z70" value=1/>较差</label>&nbsp;<label><input type=radio name="z70" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>71、市机场办</b></p></td><td><p class=select><label><input type=radio name="z71" value=4/>优秀</label>&nbsp;<label><input type=radio name="z71" value=3/>良好</label>&nbsp;<label><input type=radio name="z71" value=2/>一般</label>&nbsp;<label><input type=radio name="z71" value=1/>较差</label>&nbsp;<label><input type=radio name="z71" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>72、市政务办</b></p></td><td><p class=select><label><input type=radio name="z72" value=4/>优秀</label>&nbsp;<label><input type=radio name="z72" value=3/>良好</label>&nbsp;<label><input type=radio name="z72" value=2/>一般</label>&nbsp;<label><input type=radio name="z72" value=1/>较差</label>&nbsp;<label><input type=radio name="z72" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>73、廊坊日报社</b></p></td><td><p class=select><label><input type=radio name="z73" value=4/>优秀</label>&nbsp;<label><input type=radio name="z73" value=3/>良好</label>&nbsp;<label><input type=radio name="z73" value=2/>一般</label>&nbsp;<label><input type=radio name="z73" value=1/>较差</label>&nbsp;<label><input type=radio name="z73" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>74、廊坊广播电视台</b></p></td><td><p class=select><label><input type=radio name="z74" value=4/>优秀</label>&nbsp;<label><input type=radio name="z74" value=3/>良好</label>&nbsp;<label><input type=radio name="z74" value=2/>一般</label>&nbsp;<label><input type=radio name="z74" value=1/>较差</label>&nbsp;<label><input type=radio name="z74" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>75、廊坊职技学院</b></p></td><td><p class=select><label><input type=radio name="z75" value=4/>优秀</label>&nbsp;<label><input type=radio name="z75" value=3/>良好</label>&nbsp;<label><input type=radio name="z75" value=2/>一般</label>&nbsp;<label><input type=radio name="z75" value=1/>较差</label>&nbsp;<label><input type=radio name="z75" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>76、燕京职技学院</b></p></td><td><p class=select><label><input type=radio name="z76" value=4/>优秀</label>&nbsp;<label><input type=radio name="z76" value=3/>良好</label>&nbsp;<label><input type=radio name="z76" value=2/>一般</label>&nbsp;<label><input type=radio name="z76" value=1/>较差</label>&nbsp;<label><input type=radio name="z76" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>77、廊坊卫生学院</b></p></td><td><p class=select><label><input type=radio name="z77" value=4/>优秀</label>&nbsp;<label><input type=radio name="z77" value=3/>良好</label>&nbsp;<label><input type=radio name="z77" value=2/>一般</label>&nbsp;<label><input type=radio name="z77" value=1/>较差</label>&nbsp;<label><input type=radio name="z77" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>78、市电子信息学校</b></p></td><td><p class=select><label><input type=radio name="z78" value=4/>优秀</label>&nbsp;<label><input type=radio name="z78" value=3/>良好</label>&nbsp;<label><input type=radio name="z78" value=2/>一般</label>&nbsp;<label><input type=radio name="z78" value=1/>较差</label>&nbsp;<label><input type=radio name="z78" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>79、市电大</b></p></td><td><p class=select><label><input type=radio name="z79" value=4/>优秀</label>&nbsp;<label><input type=radio name="z79" value=3/>良好</label>&nbsp;<label><input type=radio name="z79" value=2/>一般</label>&nbsp;<label><input type=radio name="z79" value=1/>较差</label>&nbsp;<label><input type=radio name="z79" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>80、市高级技工学校</b></p></td><td><p class=select><label><input type=radio name="z80" value=4/>优秀</label>&nbsp;<label><input type=radio name="z80" value=3/>良好</label>&nbsp;<label><input type=radio name="z80" value=2/>一般</label>&nbsp;<label><input type=radio name="z80" value=1/>较差</label>&nbsp;<label><input type=radio name="z80" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>81、市体校</b></p></td><td><p class=select><label><input type=radio name="z81" value=4/>优秀</label>&nbsp;<label><input type=radio name="z81" value=3/>良好</label>&nbsp;<label><input type=radio name="z81" value=2/>一般</label>&nbsp;<label><input type=radio name="z81" value=1/>较差</label>&nbsp;<label><input type=radio name="z81" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>82、市农科院</b></p></td><td><p class=select><label><input type=radio name="z82" value=4/>优秀</label>&nbsp;<label><input type=radio name="z82" value=3/>良好</label>&nbsp;<label><input type=radio name="z82" value=2/>一般</label>&nbsp;<label><input type=radio name="z82" value=1/>较差</label>&nbsp;<label><input type=radio name="z82" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>83、市医院</b></p></td><td><p class=select><label><input type=radio name="z83" value=4/>优秀</label>&nbsp;<label><input type=radio name="z83" value=3/>良好</label>&nbsp;<label><input type=radio name="z83" value=2/>一般</label>&nbsp;<label><input type=radio name="z83" value=1/>较差</label>&nbsp;<label><input type=radio name="z83" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>84、市中医院</b></p></td><td><p class=select><label><input type=radio name="z84" value=4/>优秀</label>&nbsp;<label><input type=radio name="z84" value=3/>良好</label>&nbsp;<label><input type=radio name="z84" value=2/>一般</label>&nbsp;<label><input type=radio name="z84" value=1/>较差</label>&nbsp;<label><input type=radio name="z84" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>85、市第三医院</b></p></td><td><p class=select><label><input type=radio name="z85" value=4/>优秀</label>&nbsp;<label><input type=radio name="z85" value=3/>良好</label>&nbsp;<label><input type=radio name="z85" value=2/>一般</label>&nbsp;<label><input type=radio name="z85" value=1/>较差</label>&nbsp;<label><input type=radio name="z85" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>86、市一中</b></p></td><td><p class=select><label><input type=radio name="z86" value=4/>优秀</label>&nbsp;<label><input type=radio name="z86" value=3/>良好</label>&nbsp;<label><input type=radio name="z86" value=2/>一般</label>&nbsp;<label><input type=radio name="z86" value=1/>较差</label>&nbsp;<label><input type=radio name="z86" value=0 checked />不了解</label>&nbsp;</p></td></tr>
				<tr><td><p class=txt><b class=blue>87、管道局中学</b></p></td><td><p class=select><label><input type=radio name="z87" value=4/>优秀</label>&nbsp;<label><input type=radio name="z87" value=3/>良好</label>&nbsp;<label><input type=radio name="z87" value=2/>一般</label>&nbsp;<label><input type=radio name="z87" value=1/>较差</label>&nbsp;<label><input type=radio name="z87" value=0 checked />不了解</label>&nbsp;</p></td></tr>

			</table>
				
			<p class=sub_title><b>二、具体评价。请对所列评价单位领导班子的现实表现提出具体意见和建议。</b></p>
			<p class=txt><textarea name=suggest id=suggesttext placeholder="请输入您的意见！"></textarea></p>
			<!--<em>您还可以输入<span id=wordnum class=red>140</span>字。</em>-->
			<br>
			<input type=hidden name=step value=selectcounty />
			<input class=btn type="submit" value="提交问卷" />
			<!-- <input class=btn type="button" value="提交问卷" onClick='location.href = "thanks.html";' /> -->
		</form>
	</div>
	<?php echo '<script'; ?>
 type="text/javascript">
	$(function(){
		$("#suggesttext").keyup(function(){
			if($(this).val().length > 999){
				$(this).val($(this).val().substring(0,1000));
			}
		});
	});
	<?php echo '</script'; ?>
>
</body>
</html><?php }
}
